version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=process.env.MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=process.env.MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=process.env.MONGO_DATABASE
      - MONGO_URI=process.env.MONGO_URI
    ports:
      - 27017:27017
